apiVersion: v1
kind: Service
metadata:
  name: claims-backend
  namespace: claims-k8s
spec:
  selector:
    app: claims-backend
  ports:
    - name: http
      port: 5000
      targetPort: http
  type: ClusterIP
